import { ShapeClassName } from '@client/configs';
import clsx from 'clsx';
import Konva from 'konva';
import { ComponentProps, forwardRef, MutableRefObject } from 'react';
import { Group, Rect } from 'react-konva';

export type KeyboardProps = ComponentProps<typeof Group>;
export type KeyboardRef = Konva.Group;

export const Keyboard = forwardRef<KeyboardRef, KeyboardProps>(
  ({ name, ...props }, ref: MutableRefObject<KeyboardRef | null>) => {
    return (
      <Group
        ref={ref}
        {...props}
        name={clsx(ShapeClassName.FixedShape, ShapeClassName.Keyboard, name)}
      >
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={93}
          height={32}
          x={78}
          y={59}
          fill="#e1e1e1"
          stroke="black"
          strokeWidth={0.7}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={52}
          height={4}
          x={98}
          y={81}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={84}
          y={81}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={91}
          y={81}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={154}
          y={81}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={161}
          y={81}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />

        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={18}
          height={4}
          x={84}
          y={73}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={105}
          y={73}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={112}
          y={73}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={119}
          y={73}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={126}
          y={73}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={133}
          y={73}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={140}
          y={73}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={18}
          height={4}
          x={147}
          y={73}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />

        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={11}
          height={4}
          x={84}
          y={65}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={98}
          y={65}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={105}
          y={65}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={112}
          y={65}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={119}
          y={65}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={126}
          y={65}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={133}
          y={65}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={140}
          y={65}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={4}
          height={4}
          x={147}
          y={65}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
        <Rect
          name={clsx(ShapeClassName.FixedShapeElement)}
          width={11}
          height={4}
          x={154}
          y={65}
          fill="#a5a5a5"
          stroke="black"
          strokeWidth={0.5}
        />
      </Group>
    );
  }
);
