version: '3.8'

services:
  postgres:
    container_name: op-postgres
    image: postgres:14
    restart: always
    volumes:
      - op_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - '${DB_PORT}:5432'
    networks:
      - op-network
  redis:
    container_name: op-redis
    image: redis:7-alpine
    command: 'redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes'
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - op-network

  minio:
    container_name: op-minio
    image: quay.io/minio/minio
    restart: always
    volumes:
      - op_minio_data:/data
    ports:
      - '${MINIO_API_PORT}:9000'
      - '${MINIO_CONSOLE_PORT}:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: 'server /data --console-address ":9001"'

networks:
  op-network:

volumes:
  op_postgres_data:
  op_minio_data:
